### PR TITLE
Add onii-cogs to the list of unapproved cogs

### PR DESCRIPTION
**Pull request by Onii-Chan-Discord**

### CODE REVIEW

**Comment by Twentysix26** [comment]
@Onii-Chan-Discord you're missing a repo-level info.json, your repository will not be added until you create one

**Comment by Onii-Chan-Discord** [comment]
I have now added a repo-level info.json!

**Comment by jack1142** [comment]
@Onii-Chan-Discord FYI, the default branch (main) still does not contain the `info.json` file.

**Comment by Onii-Chan-Discord** [comment]
I'm very sorry I thought I was on the main branch at the time of the commit, but its fixed now!

**Pull request merged**
